"use client";

import { useState } from "react";
import TabInfo from "./TabInfo";
import {
  Download,
  Copy,
  Check,
  Terminal,
  AlertTriangle,
  ChevronDown,
  ChevronRight,
  Plus,
  X,
  Settings,
} from "lucide-react";

// ── Script generator ──────────────────────────────────────────────────────────

interface ScriptConfig {
  environment: string;
  outputPath: string;
  database: string;
  defaultLanguage: string;
  allLanguages: boolean;
  latestVersionOnly: boolean;
  includeFieldValues: boolean;
  excludeSystemFields: boolean;
  maxFieldValueLength: number;
  paths: string[];
}

const DEFAULT_CONFIG: ScriptConfig = {
  environment: "DEV",
  outputPath: "C:\\inetpub\\wwwroot\\snapshots",
  database: "master",
  defaultLanguage: "en",
  allLanguages: false,
  latestVersionOnly: true,
  includeFieldValues: true,
  excludeSystemFields: true,
  maxFieldValueLength: 1000,
  paths: [
    "/sitecore/templates",
    "/sitecore/layout/Renderings",
    "/sitecore/layout/Placeholder Settings",
    "/sitecore/Forms",
  ],
};

function generateScript(cfg: ScriptConfig): string {
  const pathsBlock = cfg.paths.map((p) => `    "${p}"`).join("\n");

  return `# =============================================================================
#  Export-SitecoreSnapshot.ps1
#  Run inside Sitecore PowerShell Extensions (SPE) — Script Runner or Console
#
#  Generated by Sitecore Deployment Assistant
#  Environment : ${cfg.environment}
# =============================================================================

# ── CONFIGURE BEFORE RUNNING ──────────────────────────────────────────────────

$Environment = "${cfg.environment}"

$OutputPath = "${cfg.outputPath}"

$SnapshotPaths = @(
${pathsBlock}
)

$Options = @{
    Database              = "${cfg.database}"
    DefaultLanguage       = "${cfg.defaultLanguage}"
    AllLanguages          = $${cfg.allLanguages ? "true" : "false"}
    LatestVersionOnly     = $${cfg.latestVersionOnly ? "true" : "false"}
    IncludeFieldValues    = $${cfg.includeFieldValues ? "true" : "false"}
    ExcludeSystemFields   = $${cfg.excludeSystemFields ? "true" : "false"}
    MaxFieldValueLength   = ${cfg.maxFieldValueLength}
}

# =============================================================================
#  UTILITIES
# =============================================================================

function Write-Log {
    param([string]$Message, [ValidateSet("INFO","WARN","ERROR","SUCCESS","DEBUG")][string]$Level = "INFO")
    $color = switch ($Level) {
        "INFO"    { "Cyan"   }
        "WARN"    { "Yellow" }
        "ERROR"   { "Red"    }
        "SUCCESS" { "Green"  }
        "DEBUG"   { "Gray"   }
    }
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')][$Level] $Message" -ForegroundColor $color
}

function Get-ItemFields {
    param([Sitecore.Data.Items.Item]$Item)
    $fields = [ordered]@{}
    if (-not $Options.IncludeFieldValues) { return $fields }

    $Item.Fields.ReadAll()
    foreach ($f in $Item.Fields) {
        if ($Options.ExcludeSystemFields -and $f.Name.StartsWith("__")) { continue }
        if ([string]::IsNullOrWhiteSpace($f.Value)) { continue }
        $val = $f.Value
        if ($val.Length -gt $Options.MaxFieldValueLength) {
            $val = $val.Substring(0, $Options.MaxFieldValueLength) + " ...[truncated]"
        }
        $fields[$f.Name] = $val
    }
    return $fields
}

# =============================================================================
#  SNAPSHOT EXPORT
# =============================================================================

function Export-SnapshotItems {
    param(
        [string[]]$Paths,
        [Sitecore.Data.Database]$Db
    )

    $items   = [System.Collections.Generic.List[object]]::new()
    $errors  = [System.Collections.Generic.List[object]]::new()
    $seenIds = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    $i       = 0

    foreach ($rootPath in $Paths) {
        $rootItem = $Db.GetItem($rootPath)
        if ($null -eq $rootItem) {
            Write-Log "Path not found (skip): $rootPath" "WARN"
            continue
        }
        Write-Log "Scanning: $rootPath" "INFO"

        $allItems = @($rootItem) + @($rootItem.Axes.GetDescendants())

        foreach ($item in $allItems) {
            $rawId = $item.ID.ToString()
            if (-not $seenIds.Add($rawId)) { continue }
            $i++

            Write-Progress -Activity "Exporting Snapshot" \`
                -Status "[$i] $($item.Paths.FullPath)" \`
                -PercentComplete -1

            try {
                $languages = if ($Options.AllLanguages) {
                    $item.Languages | ForEach-Object { $_.Name }
                } else {
                    @($Options.DefaultLanguage)
                }

                foreach ($langName in $languages) {
                    $lang     = [Sitecore.Globalization.Language]::Parse($langName)
                    $langItem = $Db.GetItem($item.ID, $lang)
                    if ($null -eq $langItem -or $langItem.Versions.Count -eq 0) { continue }

                    $versions = if ($Options.LatestVersionOnly) {
                        @($langItem.Versions.GetLatestVersion())
                    } else {
                        @($langItem.Versions.GetVersions())
                    }

                    foreach ($ver in $versions) {
                        if ($null -eq $ver) { continue }
                        $ver.Fields.ReadAll()

                        $items.Add([ordered]@{
                            id           = $ver.ID.ToString()
                            name         = $ver.Name
                            path         = $ver.Paths.FullPath
                            templateId   = $ver.TemplateID.ToString()
                            templateName = $ver.TemplateName
                            parentId     = $ver.ParentID.ToString()
                            language     = $langName
                            version      = $ver.Version.Number
                            created      = $ver.Fields["__Created"].Value
                            createdBy    = $ver.Fields["__Created by"].Value
                            updated      = $ver.Fields["__Updated"].Value
                            updatedBy    = $ver.Fields["__Updated by"].Value
                            revision     = $ver.Fields["__Revision"].Value
                            fields       = Get-ItemFields -Item $ver
                        })
                    }
                }
            } catch {
                Write-Log "FAILED: $($item.Paths.FullPath) -- $_" "ERROR"
                $errors.Add([ordered]@{
                    itemPath = $item.Paths.FullPath
                    itemId   = $rawId
                    error    = $_.ToString()
                })
            }
        }
    }

    Write-Progress -Activity "Exporting Snapshot" -Completed
    return @{ items = $items.ToArray(); errors = $errors.ToArray() }
}

# =============================================================================
#  MAIN
# =============================================================================

$startTime = Get-Date
Write-Log "================================================" "INFO"
Write-Log "  Sitecore Snapshot Export"                        "INFO"
Write-Log "  Environment : $Environment"                      "INFO"
Write-Log "  Database    : $($Options.Database)"              "INFO"
Write-Log "  Started     : $($startTime.ToString('yyyy-MM-dd HH:mm:ss'))" "INFO"
Write-Log "================================================" "INFO"

$db     = [Sitecore.Configuration.Factory]::GetDatabase($Options.Database)
$result = Export-SnapshotItems -Paths $SnapshotPaths -Db $db

$durationMs = [int]((Get-Date) - $startTime).TotalMilliseconds

$output = [ordered]@{
    "_schemaVersion" = "1.0"
    "_exportedAt"    = $startTime.ToString("o")
    "_environment"   = $Environment

    "exportConfig"   = [ordered]@{
        environment         = $Environment
        database            = $Options.Database
        snapshotPaths       = @($SnapshotPaths)
        allLanguages        = $Options.AllLanguages
        defaultLanguage     = $Options.DefaultLanguage
        latestVersionOnly   = $Options.LatestVersionOnly
        includeFieldValues  = $Options.IncludeFieldValues
        excludeSystemFields = $Options.ExcludeSystemFields
    }

    "summary"        = [ordered]@{
        environment  = $Environment
        totalItems   = $result.items.Count
        totalErrors  = $result.errors.Count
        durationMs   = $durationMs
    }

    "items"          = $result.items
    "errors"         = $result.errors
}

$json       = $output | ConvertTo-Json -Depth 20 -Compress
$fileSizeKb = [math]::Round([System.Text.Encoding]::UTF8.GetByteCount($json) / 1KB, 1)
$fileName   = "sitecore-snapshot.$Environment.$(Get-Date -Format 'yyyyMMdd-HHmm').json"
$filePath   = Join-Path $OutputPath $fileName

if (-not (Test-Path $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}

[System.IO.File]::WriteAllText($filePath, $json, [System.Text.Encoding]::UTF8)
$json | Out-Download -Name $fileName

Write-Log "================================================" "SUCCESS"
Write-Log "  EXPORT COMPLETE"                                  "SUCCESS"
Write-Log "  File       : $filePath  ($fileSizeKb KB)"         "SUCCESS"
Write-Log "  Items      : $($result.items.Count)"              "SUCCESS"
Write-Log "  Errors     : $($result.errors.Count)"             "SUCCESS"
Write-Log "  Duration   : $durationMs ms"                      "SUCCESS"
Write-Log "================================================" "SUCCESS"
`;
}

// ── UI helpers ────────────────────────────────────────────────────────────────

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      onClick={copy}
      className="flex items-center gap-1 px-2 py-1 rounded text-xs text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
    >
      {copied ? (
        <Check className="h-3.5 w-3.5 text-emerald-500" />
      ) : (
        <Copy className="h-3.5 w-3.5" />
      )}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

function Toggle({
  value,
  onChange,
  label,
}: {
  value: boolean;
  onChange: (v: boolean) => void;
  label: string;
}) {
  return (
    <label
      className="flex items-center gap-2.5 cursor-pointer select-none"
      onClick={() => onChange(!value)}
    >
      <div
        className={`relative w-9 h-5 rounded-full transition-colors shrink-0 ${value ? "bg-slate-800" : "bg-slate-300"}`}
      >
        <span
          className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-transform ${value ? "translate-x-4" : "translate-x-0.5"}`}
        />
      </div>
      <span className="text-sm text-slate-700">{label}</span>
    </label>
  );
}

const ENVS = ["DEV", "UAT", "PROD", "DR"];
const DBS = ["master", "web"];

// ── Main component ────────────────────────────────────────────────────────────

export default function SetupView() {
  const [cfg, setCfg] = useState<ScriptConfig>(DEFAULT_CONFIG);
  const [newPath, setNewPath] = useState("");
  const [showPreview, setShowPreview] = useState(false);

  const set = <K extends keyof ScriptConfig>(key: K, val: ScriptConfig[K]) =>
    setCfg((c) => ({ ...c, [key]: val }));

  const addPath = () => {
    const p = newPath.trim();
    if (p && !cfg.paths.includes(p)) {
      set("paths", [...cfg.paths, p]);
      setNewPath("");
    }
  };

  const removePath = (p: string) =>
    set(
      "paths",
      cfg.paths.filter((x) => x !== p),
    );

  const downloadScript = () => {
    const script = generateScript(cfg);
    const blob = new Blob([script], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Export-SitecoreSnapshot.${cfg.environment}.ps1`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const script = generateScript(cfg);

  return (
    <div className="flex-1 flex flex-col overflow-hidden bg-slate-50">
      <TabInfo
        title="Setup Instructions"
        what="Generate and download a custom PowerShell script to capture a snapshot of any Sitecore environment."
        how="Configure your environment name, server output path, and which Sitecore content trees to include. The script runs inside Sitecore PowerShell Extensions (SPE) and downloads the snapshot JSON directly to your browser."
        helps="Gives you a reliable, repeatable baseline of any environment in minutes. The snapshot is the foundation for all risk analysis — without it you are comparing packages against nothing."
        avoids="Manual, error-prone environment audits. Removes the need to guess what is already deployed in UAT or PROD before pushing a new package."
      />
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-2xl mx-auto px-6 py-8 space-y-6">
          {/* Header */}
          <div className="space-y-1">
            <div className="flex items-center gap-2.5">
              <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-slate-900">
                <Terminal className="h-4 w-4 text-white" />
              </div>
              <h1 className="text-xl font-bold text-slate-900">
                Snapshot Export Script
              </h1>
            </div>
            <p className="text-sm text-slate-500 pl-[42px]">
              Configure and download a PowerShell script to run inside Sitecore
              PowerShell Extensions (SPE). The snapshot JSON it produces is
              required for risk analysis.
            </p>
          </div>

          {/* Config card */}
          <div className="bg-white border border-slate-200 rounded-xl divide-y divide-slate-100">
            {/* Environment + DB */}
            <div className="px-5 py-4 space-y-4">
              <h2 className="text-xs font-semibold text-slate-500 uppercase tracking-wide flex items-center gap-1.5">
                <Settings className="h-3.5 w-3.5" /> General
              </h2>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-medium text-slate-600">
                    Environment
                  </label>
                  <div className="flex gap-1.5 flex-wrap">
                    {ENVS.map((e) => (
                      <button
                        key={e}
                        onClick={() => set("environment", e)}
                        className={`px-3 py-1 rounded-md text-xs font-semibold border transition-colors
                        ${
                          cfg.environment === e
                            ? "bg-slate-900 text-white border-slate-900"
                            : "bg-white text-slate-600 border-slate-200 hover:border-slate-400"
                        }`}
                      >
                        {e}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-medium text-slate-600">
                    Database
                  </label>
                  <div className="flex gap-1.5">
                    {DBS.map((db) => (
                      <button
                        key={db}
                        onClick={() => set("database", db)}
                        className={`px-3 py-1 rounded-md text-xs font-semibold border transition-colors
                        ${
                          cfg.database === db
                            ? "bg-slate-900 text-white border-slate-900"
                            : "bg-white text-slate-600 border-slate-200 hover:border-slate-400"
                        }`}
                      >
                        {db}
                      </button>
                    ))}
                  </div>
                  <p className="text-[11px] text-slate-400">
                    For Master vs Web drift, download once per database.
                  </p>
                </div>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-600">
                  Output path (server folder)
                </label>
                <input
                  value={cfg.outputPath}
                  onChange={(e) => set("outputPath", e.target.value)}
                  className="w-full text-sm border border-slate-200 rounded-lg px-3 py-1.5 font-mono focus:outline-none focus:ring-2 focus:ring-slate-400"
                />
              </div>
            </div>

            {/* Snapshot paths */}
            <div className="px-5 py-4 space-y-3">
              <h2 className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
                Paths to snapshot
              </h2>
              <div className="space-y-1.5">
                {cfg.paths.map((p) => (
                  <div
                    key={p}
                    className="flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-lg px-3 py-2"
                  >
                    <code className="flex-1 text-xs font-mono text-slate-700">
                      {p}
                    </code>
                    <button
                      onClick={() => removePath(p)}
                      className="text-slate-300 hover:text-red-500 transition-colors"
                    >
                      <X className="h-3.5 w-3.5" />
                    </button>
                  </div>
                ))}
              </div>
              <div className="flex gap-2">
                <input
                  value={newPath}
                  onChange={(e) => setNewPath(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && addPath()}
                  placeholder="/sitecore/content/YourSite"
                  className="flex-1 text-sm border border-slate-200 rounded-lg px-3 py-1.5 font-mono focus:outline-none focus:ring-2 focus:ring-slate-400 placeholder:text-slate-300"
                />
                <button
                  onClick={addPath}
                  disabled={!newPath.trim()}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-900 text-white text-xs font-medium hover:bg-slate-700 disabled:opacity-40 transition-colors"
                >
                  <Plus className="h-3.5 w-3.5" /> Add
                </button>
              </div>
              <div className="flex items-start gap-2 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
                <AlertTriangle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
                <span>
                  Adding large content trees will significantly increase
                  snapshot size and export time.
                </span>
              </div>
            </div>

            {/* Options */}
            <div className="px-5 py-4 space-y-3">
              <h2 className="text-xs font-semibold text-slate-500 uppercase tracking-wide">
                Options
              </h2>
              <div className="grid grid-cols-2 gap-3">
                <Toggle
                  value={cfg.allLanguages}
                  onChange={(v) => set("allLanguages", v)}
                  label="All languages"
                />
                <Toggle
                  value={cfg.latestVersionOnly}
                  onChange={(v) => set("latestVersionOnly", v)}
                  label="Latest version only"
                />
                <Toggle
                  value={cfg.includeFieldValues}
                  onChange={(v) => set("includeFieldValues", v)}
                  label="Include field values"
                />
                <Toggle
                  value={cfg.excludeSystemFields}
                  onChange={(v) => set("excludeSystemFields", v)}
                  label="Exclude system fields"
                />
              </div>
              {cfg.includeFieldValues && (
                <div className="flex items-center gap-3">
                  <label className="text-xs font-medium text-slate-600 shrink-0">
                    Max field length
                  </label>
                  <input
                    type="number"
                    value={cfg.maxFieldValueLength}
                    onChange={(e) =>
                      set("maxFieldValueLength", Number(e.target.value))
                    }
                    className="w-24 text-sm border border-slate-200 rounded-lg px-3 py-1.5 focus:outline-none focus:ring-2 focus:ring-slate-400"
                  />
                  <span className="text-xs text-slate-400">characters</span>
                </div>
              )}
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-3">
            <button
              onClick={downloadScript}
              className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-slate-900 text-white text-sm font-semibold hover:bg-slate-700 transition-colors"
            >
              <Download className="h-4 w-4" />
              Download Export-SitecoreSnapshot.{cfg.environment}.ps1
            </button>
            <button
              onClick={() => setShowPreview((p) => !p)}
              className="flex items-center gap-1.5 px-4 py-2.5 rounded-lg border border-slate-200 bg-white text-sm font-medium text-slate-600 hover:bg-slate-50 transition-colors"
            >
              {showPreview ? (
                <ChevronDown className="h-4 w-4" />
              ) : (
                <ChevronRight className="h-4 w-4" />
              )}
              {showPreview ? "Hide" : "Preview"} script
            </button>
          </div>

          {/* Script preview */}
          {showPreview && (
            <div className="relative">
              <pre className="bg-slate-950 text-slate-200 text-xs rounded-xl px-5 py-4 overflow-x-auto font-mono leading-relaxed max-h-[500px] overflow-y-auto">
                {script}
              </pre>
              <div className="absolute top-3 right-3">
                <CopyButton text={script} />
              </div>
            </div>
          )}

          {/* How to run */}
          <div className="border border-slate-200 rounded-xl bg-white divide-y divide-slate-100 overflow-hidden">
            <div className="px-5 py-3 bg-slate-50">
              <h2 className="text-xs font-semibold text-slate-600 uppercase tracking-wide">
                How to run
              </h2>
            </div>
            {[
              {
                n: 1,
                text: "Log in to Sitecore and open PowerShell ISE from the Desktop → PowerShell Toolbox.",
              },
              {
                n: 2,
                text: "Download and open the script above in the SPE editor (or paste directly into the console).",
              },
              {
                n: 3,
                text: "Press F5 or click Run. A progress bar will show items being scanned.",
              },
              {
                n: 4,
                text: "When complete the browser will prompt you to download the .json snapshot file.",
              },
              {
                n: 5,
                text: "Go to the Risk Analyzer tab, load the snapshot, add your packages, then click Run Risk Analysis.",
              },
            ].map((s) => (
              <div key={s.n} className="flex items-start gap-3 px-5 py-3">
                <span className="flex items-center justify-center w-5 h-5 rounded-full bg-slate-900 text-white text-xs font-bold shrink-0 mt-0.5">
                  {s.n}
                </span>
                <p className="text-sm text-slate-600">{s.text}</p>
              </div>
            ))}
          </div>

          {/* Requirements */}
          <div className="border border-slate-200 rounded-xl bg-white px-5 py-4 space-y-2">
            <h2 className="text-sm font-semibold text-slate-700">
              Requirements
            </h2>
            <ul className="space-y-1.5 text-sm text-slate-600">
              {[
                "Sitecore 9.x or later",
                "Sitecore PowerShell Extensions (SPE) 6.x or later",
                "Admin or PowerShell-enabled Sitecore account",
                "Write access to the output folder on the server",
              ].map((r) => (
                <li key={r} className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-slate-400 shrink-0" />
                  {r}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
